version: '3.5'
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
  command: server http://minio{1...4}/data{1...2}
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
    interval: 30s
    timeout: 20s
    retries: 3
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ACCESS_KEY: ACCESS_KEY
    MINIO_SECRET_KEY: SECRET_KEY

services:
  crdb:
   container_name: crdb
   image: cockroachdb/cockroach:latest
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure 
   volumes:
     - ./data/node_1:/cockroach/cockroach-data
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./s3/data1-1:/data1
      - ./s3/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./s3/data2-1:/data1
      - ./s3/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ./s3/data3-1:/data1
      - ./s3/data3-2:/data2
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - ./s3/data4-1:/data1
      - ./s3/data4-2:/data2
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nest
    command: npm run start:dev
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
    env_file:
      - .env


